# -*- coding: utf-8 -*-
"""Data Science - Raspagem de Dados de Sites na Internet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AajgXyoW3w4GVpQeYTvBtZsZEYllZHh4
"""

import re
from bs4 import BeautifulSoup
from requests import get
r = get('https://pizzadedados.com')
sopa = BeautifulSoup(r.content.decode('utf-8'), 'html.parser')

print(sopa.prettify()[:100])

for link in sopa.find_all('a'):
    print(link.get('href'))